### ISSUE TITLE
The latest code contains compilation errors

### ISSUE THREAD

**Issue by lqcspring** [dbiir/Poem#1]
The latest code contains compilation errors. After merging the code conflicts in the file, there are syntax errors in the file migrate_thread.cpp.Could it be that the author failed to submit part of the code?
